site_name: bluebird-dt

plugins:
  - macros:
       modules: [docs.get_version]

nav:
  - ATC concepts and terminology:
      - Overview: ./#atc-concepts-and-terminology
      - Aircraft: ./#aircraft
      - Sector: ./#sector
      - Fix: ./#fix
      - Route: ./#route
      - Airspace: ./#airspace
      - Action: ./#action
      - Sectors:
          - Overview: ./#sectors
          - I-sector: ./#i-sector
          - Y-sector: ./#y-sector
          - X-sector: ./#x-sector
          - Xplus-sector: ./#xplus-sector
          - Springfield: ./#springfield
      - Scenarios:
          - Overview: ./#scenarios
          - Two Aircraft: ./#two-aircraft
          - Regular: ./#regular
          - Tactical: ./#tactical
          - Infinite: ./#infinite
      - Design of the digital twin:
          - Overview: ./#design-of-the-digital-twin
          - Core classes: ./#core-classes
          - Scenario and airspace generators: ./#scenario-and-airspace-generators
          - Simulation and event management: ./#simulation-and-event-management
          - Predictors: ./#predictors
          - Utility functions: ./#utility-functions
  - Developer Guide:
      - Overview: ./#developer-guide
      - Installing the software: ./#installing-the-software
      - Unit testing: ./#unit-testing
      - Running tests: ./#running-tests
  - Source code reference: source.md
