site_name: bluebird-api

nav:
  - Terminology: ./#terminology
  - Using the pre-built API: ./#using-the-pre-built-api
  - Developer Guide:
      - Overview: ./#developer-guide
      - Running locally: ./#running-locally
      - Running tests and checks: ./#running-tests-and-checks
      - Source README: ./#source-readme
  - Source code reference: source.md
