site_name: bluebird-gymnasium

plugins:
  - macros:
       modules: [docs.get_version]

nav:
  - Introduction:
      - Overview: ./
      - Installation: ./#installation
      - Simple usage: ./#simple-usage
      - Getting started: ./#getting-started
  - Reward functions: rewards.md
  - Actions: actions.md
  - State representations: state_representations.md
  - Agent view: agent_view.md
  - Environment configurations: configurations.md
  - Source code reference: source.md
